server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: orderService
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000  # 连接超时 2000ms


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000

#把hystrix 超时时间关闭
hystrix:
  command:
    default:
      execution:
         isolation:
           thread:
             timeoutInMilliseconds: 4000



#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"